### ISSUE TITLE
Change order of package name

### ISSUE THREAD

**Issue by artelse** [jgru/consult-org-roam#1]
Hi,
just tested `org-roam-consult` and it works as expected, love it!
As a matter of consistency with naming consult extensions, I would suggest naming it `consult-org-roam`.
Thanks.
Edit: I did get some warnings, but that's expected with a WIP ;)

**Comment by jgru** [comment]
Hi @artelse,
thanks for you interest in the package and you suggestion. 
Since it sounds like a good idea to follow `consult`'s naming conventions, I changed the repo's name and the whole code base to conform with that in commit [e1ff4b1](https://github.com/jgru/consult-org-roam/commit/e1ff4b169fab42ebe254d15ae11165996448646a).

Thanks for that remark!

Can you please elaborate what warnings you observed?

**Comment by artelse** [comment]
These are the warnings:
```
Warning (comp): consult-org-roam.el:11:12: Warning: defcustom for ‘consult-org-roam-grep-func’ fails to specify containing group Disable showing Disable logging
Warning (comp): consult-org-roam.el:11:12: Warning: defcustom for ‘consult-org-roam-grep-func’ fails to specify containing group Disable showing Disable logging
Warning (comp): consult-org-roam.el:47:11: Warning: Unused lexical variable `node' Disable showing Disable logging
Warning (comp): consult-org-roam.el:82:2: Warning: docstring wider than 80 characters Disable showing Disable logging
Warning (comp): consult-org-roam.el:82:70: Warning: Unused lexical argument `require-match' Disable showing Disable logging
```
Some are because of more strict warnings in Emacs 29 I belief.

**Comment by jgru** [comment]
Thanks for sharing these warnings with me, @artelse. 
I think they should be addressed by commit [a6f3aed](https://github.com/jgru/consult-org-roam/commit/a6f3aed8b473a469c8496cbd0f8493b10c7e453b). 
Could you check, whether those newly added changes resolve the a/m warnings? 
Thanks in advance!

**Comment by artelse** [comment]
That commit fixes most of them, just one remaining, but that seems harmless:
`Warning (comp): consult-org-roam.el:91:2: Warning: docstring wider than 80 characters Disable showing Disable logging`
Thanks, I like this package, makes org-roam even more enjoyable to work with.

**Comment by jgru** [comment]
This should now be fixed with [8c5cb9d](https://github.com/jgru/consult-org-roam/commit/8c5cb9d5ae2170cdbc427e8da7a9a6eebb226e9d).
Thanks for reporting those warnings. Can we close this issue?

**Comment by artelse** [comment]
That resolved the last warning. Don't want to open another issue, but don't see a version string of the package in completion buffer.

**Comment by jgru** [comment]
Good point, thanks!
I added a version string and some commentary in commit 5ed4caa.
If you find any other issues, please let me know. 

Best regards,
jgru
