### ISSUE TITLE
consult-buffer doesn't show capture buffers

### ISSUE THREAD

**Issue by bram85** [jgru/consult-org-roam#18]
With consult-org-roam enabled, capture buffers are no longer listed with consult-buffer. They are visible with switch-to-buffer or when I disable this package.

And not sure if this is related to this bug or even related to this package, or more Consult / Marginalia related, but an error appears when I press the narrow button for the org-roam category while having a capture open (wrong-type-argument stringp nil).

[Backtrace](https://apps.bram85.nl/bin/?7fe8654e99772623#7UdVUKgpU7CiBxCr7moKF4h9rfzPWxwS51T4K3uQ8rVX)

**Comment by jgru** [comment]
Hi @bram85, 

thank you for reporting this issue. I think this is related of how `consult-org-roam-buffer` deals with org-roam-buffers that have not been written to the roam-db yet. I expect the error to happen somewhere around here 

https://github.com/jgru/consult-org-roam/blob/6f64973ca132217b9689c6140e5e2b7c598f6fbb/consult-org-roam-buffer.el#L61-L68

I need to investigate this more closely when time permits. 

Best regards,
jgru

**Comment by jgru** [comment]
Hi @bram85, 

commit https://github.com/jgru/consult-org-roam/commit/11678329d5906ab6f91d8fbea15c283ffed93987 should fix the issue. Could you please this and confirm that these changes resolve the bug for you?

Best regards,
jgru

**Comment by bram85** [comment]
Nice, it works. Thank you 🙂

**Comment by jgru** [comment]
> Nice, it works. Thank you slightly_smiling_face

Good to hear. You are welcome. Happy that you use this package.
