### ISSUE TITLE
consult-org-roam-buffer, do not alter visiting order of buffers

### ISSUE THREAD

**Issue by dmgerman** [jgru/consult-org-roam#28]
thank you the package

I wonder if it would be possible to add a variable that will permit the buffers to be kept in their visited order (last visited top) instead of moving them all to their own section.

Here is my use case: I use org-roam dailies. So I am constantly going back to the buffer of today.

With consult-org-roam-mode enabled, today's note is now way down and I have to type first n to be able to see it. Which means every time I am switching buffers I have to think: is this a roam node or not before I can see in the list of buffers.

it is nice though to have the option to narrow the buffers using n though.

**Comment by jgru** [comment]
Hello @dmgerman,

thanks for opening this issue. I added a `defcustom` named `consult-org-roam-buffer-enabled` to selectively disable `consult-org-roam-buffer` in commit 2ca42a1c1641a29f1447d35be01bd1fda368a9e2.

The functionality in `consult-org-roam-buffer.el` groups the notes in a dedicated `consult-buffer-source`-category what leads to moving the notes "way down" (as you called it) grouping those in their own category. By setting the a/m `defcustom` to `nil`, this grouping and ordering can now be disabled. 

I don't think that it is (easily) possible to have narrowing without showing those notes in a dedicated `consult-buffer-source`. So it is a trade-off between narrowing and retaining "visited order".

Does this solve your issue? 

Best regards,
jgru

**Comment by jgru** [comment]
Hi @dmgerman,

does this change solve the issue for you?

Best regards,
jgru

**Comment by dmgerman** [comment]
Sorry it took me this time to reply. I had to rewrite my config to read from github instead of melpa.

Yes, I set the variable to t, and now it works very since, since I can still narrow the org-roam buffers with n<space>

I truly appreciate it (and again, sorry for the delay)

**Comment by mateialexandru** [comment]
Thank you! Had the same issue, and setting  (setq consult-org-roam-buffer-enabled nil) helped!
