### ISSUE TITLE
How to jump to the search result?

### ISSUE THREAD

**Issue by weirdvic** [jgru/consult-org-roam#29]
Hello I thik my issue could be trivial but I could not find an answer in the readme.

I'm using consult-org-roam with pretty default config:
```elisp
(use-package consult-org-roam
   :after org-roam
   :init
   (require 'consult-org-roam)
   ;; Activate the minor mode
   (consult-org-roam-mode 1)
   :custom
   ;; Use `ripgrep' for searching with `consult-org-roam-search'
   (consult-org-roam-grep-func #'consult-ripgrep)
   ;; Configure a custom narrow key for `consult-buffer'
   (consult-org-roam-buffer-narrow-key ?r)
   ;; Display org-roam buffers right after non-org-roam buffers
   ;; in consult-buffer (and not down at the bottom)
   (consult-org-roam-buffer-after-buffers t)
   :config
   ;; Eventually suppress previewing for certain functions
   (consult-customize
    consult-org-roam-forward-links
    :preview-key (kbd "M-."))
   :bind
   ;; Define some convenient keybindings as an addition
   ("C-c n e" . consult-org-roam-file-find)
   ("C-c n b" . consult-org-roam-backlinks)
   ("C-c n r" . consult-org-roam-search))
```

When I'm using `consult-org-roam-search`, the searching itself works good and I see list of results but can't easily jump to the current highlighted search result.
I have tried `<RET>`, `C-j`, `M-j` but they all produce the same message to the Messages buffer:
```
Wrong type argument: number-or-marker-p, nil
```

**Comment by jgru** [comment]
Hi @weirdvic,

which completion UI do you use?

**Comment by weirdvic** [comment]
Thank you for the fast reply!
I was using fido-mode but now I have upgraded to vertico and it's all working great now.

**Comment by jgru** [comment]
Good to hear that this solved it for you, @weirdvic!
Have fun using the package!
