### ISSUE TITLE
Org heading node is not searched

### ISSUE THREAD

**Issue by teeann** [jgru/consult-org-roam#30]
Calling `consult-org-roam-file-find` does not search Org heading by default

**Comment by jgru** [comment]
Hi @teeann,

thanks for opening this. Actually, the intended functionality of `consult-org-roam-file-find` is to search the filename and not the heading. You can search for headings using `org-roam-node-find` after activating the `consult-org-roam`-minor mode. 
Would you please try that out and report whether this solves your issue?

Best,
jgru

**Comment by teeann** [comment]
Hi, I've tried your solution and it works as intended. Thank you!

**Comment by jgru** [comment]
> Hi, I've tried your solution and it works as intended. Thank you!

Good to hear! I hope you enjoy using `consult-org-roam`.
