### ISSUE TITLE
consult-org-roam-forward-links is not working

### ISSUE THREAD

**Issue by drcxd** [jgru/consult-org-roam#31]
After executing `consult-org-roam-forward-links` I get an error message:

```
consult--key-parse: [134217774] is not a valid key definition; see ‘key-valid-p’
```

I found a related issue: https://github.com/minad/consult/issues/747 but I have not figured out how to fix this problem. Can you help?

**Comment by drcxd** [comment]
I have figured out that the problem is in the sample customization code:

```
   ;; Eventually suppress previewing for certain functions
   (consult-customize
    consult-org-roam-forward-links
    :preview-key (kbd "M-."))
```

Looks like it has to be:

```
   ;; Eventually suppress previewing for certain functions
   (consult-customize
    consult-org-roam-forward-links
    :preview-key "M-.")
```

Maybe you can update the README file?

**Comment by jgru** [comment]
Hi @drcxd,

thank you very much for pointing this out.
Indeed, we need to drop the `(kbd ...)` to avoid this error with `consult`'s  key parsing checks. 
I already updated the readme in 47e43a7ffa703b1cc4c73cae953dadea4eff83df.

Thanks again.

Best,
jgru
