### ISSUE TITLE
Change default `#'consult-org-roam-grep-func`

### ISSUE THREAD

**Issue by josephmturner** [jgru/consult-org-roam#9]
Hello!

May I suggest setting the default value `#'consult-org-roam-grep-func` to `#'consult-grep`?

This change would ensure that users who do not have ripgrep installed are able to use this package OOTB.

Thank you!

**Comment by jgru** [comment]
Hello @josephmturner,

thank you for this suggestion of more sensible defaults. Indeed, this is very beneficial; therefore, I incorporated the change in 6e676a81b1cf769637fcd666a2423d70cfe9d8b1. 

Best regards,
jgru

**Comment by josephmturner** [comment]
Thank you!!
